In [10]:
!python -m pip install pandas

Collecting pandas
  Downloading pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\abhim\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhim\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\abhim\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.1-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.2/11.5 MB 5.1 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/11.5 MB 10.1 MB/s eta 0:00:02
   ----- ---------------------------------- 1.5/11.5 MB 13.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.5/11.5 MB 15.8 MB/s eta 0:00:01
   ---------- ----------------------------- 3.1/11.5 MB 16.6 MB/s eta 0:00:01
   ------------- -------------------------- 4.0/11.5 MB 17.0 MB/s eta 0:00:01
   ----------------- ---------------------- 5.0/11.5 MB 17.5 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.5 MB 18.5 MB/s eta 0:00:01
   ----------------------- ---------------- 6.8/11.5 MB 18.8 MB/s eta 0:00:01
   -------------------------- ------------- 7.7/11.5 MB 18.8 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.5 MB 19.9 MB/s eta 0:00:01
   -------------------------------- ------- 9.4/11.5 MB 19.3 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 21.1 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 21.1 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ---------------------------------------- 0.0/505.5 kB ? eta -:--:--
   --------------------------------------- 505.5/505.5 kB 16.0 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ---------------------------------------- 0.0/345.4 kB ? eta -:--:--
   --------------------------------------- 345.4/345.4 kB 10.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.1 pytz-2024.1 tzdata-2024.1

In [2]:
import pandas as pd

In [19]:
df = pd.read_csv("data.csv")
df

,Unnamed: 0,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...
145,145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [20]:
df = df.drop("Unnamed: 0", axis=1)
df = df.drop("Id", axis=1)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [21]:
df.to_csv("data.csv", index=False)